---

- name: Take a coffee and let your Ansible setup your computer :-)
  hosts: localhost
  vars_files:
    - vars/config.yml
  roles:
    - { role: cmprescott.chrome, become: yes }
    - { role: tersmitten.phpstorm, become: yes  }
    - { role: jbeurel.webstorm, become: yes }
    - { role: kosssi.gitconfig }
    - { role: sublimeLikeTheme }
    - { role: tmux, become: yes }
